symfony/ai

demo/composer.lock
examples/composer.json
src/agent/composer.json
src/ai-bundle/composer.json
src/mcp-bundle/composer.json
src/platform/composer.json
src/store/composer.json

adopting packagist packages since the split is done :)

remove path repositories since we have packages now

---

src/agent/composer.json
src/agent/src/Chat/MessageStore/CacheStore.php
src/agent/src/Chat/MessageStore/SessionStore.php
src/agent/src/Toolbox/Tool/Crawler.php
src/agent/src/Toolbox/Tool/YouTubeTranscriber.php
src/platform/composer.json
src/platform/src/Bridge/Bedrock/PlatformFactory.php
src/platform/src/Bridge/TransformersPHP/PlatformFactory.php
src/store/composer.json
src/store/src/Bridge/ChromaDB/Store.php
src/store/src/Bridge/MariaDB/Store.php
src/store/src/Bridge/MongoDB/Store.php
src/store/src/Bridge/Pinecone/Store.php

| New feature?  |no
| Issues        | Fix #76 
Cherry picking https://github.com/php-llm/llm-chain/pull/385
> Remove the `suggest` section from composer.json and add explicit runtime checks
that throw exceptions with helpful composer require commands when optional
dependencies are missing.
> 
> This provides better developer experience by:
> - Giving clear error messages when optional dependencies are needed
> - Providing the exact composer command to install missing packages
> - Following Symfony's pattern for handling optional dependencies
> 
> Optional dependencies now throw exceptions instead of silently failing when the required packages are not installed.

refactor: replace composer suggests with runtime checks

---

examples/.env
examples/compose.yaml
examples/store/meilisearch-similarity-search.php
src/store/doc/index.rst
src/store/src/Bridge/Meilisearch/Store.php
src/store/tests/Bridge/Meilisearch/StoreTest.php

| Issues        | Fix #93 
Hi 👋🏻 
As explained in #93, this PR aim to add `meilisearch` as a vector store, the full integration is not finished (tests to be validated) but the main implementation is ready.

[Store] Add Meilisearch

---

src/ai-bundle/composer.json
src/ai-bundle/config/services.php
src/ai-bundle/doc/index.rst
src/ai-bundle/phpstan.dist.neon
src/ai-bundle/src/Security/Attribute/IsGrantedTool.php
src/ai-bundle/src/Security/EventListener/IsGrantedToolAttributeListener.php
src/ai-bundle/tests/Fixture/Tool/ToolWithIsGrantedOnClass.php
src/ai-bundle/tests/Fixture/Tool/ToolWithIsGrantedOnMethod.php
src/ai-bundle/tests/Security/IsGrantedToolAttributeListenerTest.php

| Issues        | Fix https://github.com/php-llm/llm-chain/issues/360
Add `#[IsGrantedTool]` attribute for tool access control with similar behavior as `#[IsGranted]` in `symfony/security-http`.
Moved from https://github.com/php-llm/llm-chain/pull/382

[AIBundle] Add `#[IsGrantedTool]` for tool access control

---

src/platform/src/Message/AssistantMessage.php
src/platform/src/Message/MessageInterface.php
src/platform/src/Message/SystemMessage.php
src/platform/src/Message/ToolCallMessage.php
src/platform/src/Message/UserMessage.php
src/platform/tests/ContractTest.php
src/platform/tests/Message/AssistantMessageTest.php
src/platform/tests/Message/SystemMessageTest.php
src/platform/tests/Message/ToolCallMessageTest.php
src/platform/tests/Message/UserMessageTest.php

Cherry picking https://github.com/php-llm/llm-chain/pull/384

[Platform] Use intersection type `AbstractUid&TimeBasedUidInterface` for flexible message IDs

---

src/agent/phpstan.dist.neon

Cherry picking https://github.com/php-llm/llm-chain/pull/389

[Agent] Use PHPStan error identifier instead of regex pattern

---

src/platform/composer.json
src/platform/src/Bridge/Azure/OpenAI/EmbeddingsModelClient.php
src/platform/src/Bridge/Azure/OpenAI/GPTModelClient.php
src/platform/src/Bridge/Azure/OpenAI/WhisperModelClient.php
src/platform/src/Bridge/OpenAI/DallE/Base64Image.php
src/platform/src/Bridge/OpenAI/DallE/ModelClient.php
src/platform/src/Bridge/OpenAI/DallE/UrlImage.php
src/platform/src/Bridge/OpenAI/Embeddings/ModelClient.php
src/platform/src/Bridge/OpenAI/GPT/ModelClient.php
src/platform/src/Bridge/OpenAI/Whisper/ModelClient.php
src/platform/src/Bridge/OpenRouter/Client.php
src/platform/src/Bridge/Replicate/LlamaModelClient.php
src/platform/src/Contract/JsonSchema/Attribute/With.php
src/platform/tests/Bridge/Azure/OpenAI/EmbeddingsModelClientTest.php
src/platform/tests/Bridge/Azure/OpenAI/GPTModelClientTest.php
src/platform/tests/Bridge/Azure/OpenAI/WhisperModelClientTest.php
src/platform/tests/Bridge/OpenAI/DallE/ModelClientTest.php
src/platform/tests/Contract/JsonSchema/Attribute/ToolParameterTest.php
src/store/composer.json
src/store/src/Document/TextDocument.php

| Issues        | none
Hi,
I am not sure w need the `webmozart/assert` dependency for just one verification.
Let me squash this PR before any action (I am not with my usual setup at the moment).
Regards.

[AI Store] Remove `webmozart/assert` library

---

src/platform/src/Bridge/Mistral/TokenOutputProcessor.php
src/platform/tests/Bridge/Mistral/TokenOutputProcessorTest.php

Add a TokenOutputProcessor for the Mistral platform, like it exists for the OpenAI one.

[Platform] Add `TokenOutputProcessor` for `Mistral`

---

examples/compose.yaml

Officiel PGVector Docker image is https://hub.docker.com/r/pgvector/pgvector/tags
The previous one is marked as abandoned https://hub.docker.com/r/ankane/pgvector

fix(store): Change pgvector Docker image to the official up to date one

---

examples/store/memory-similarity-search.php
src/store/doc/index.rst
src/store/src/InMemoryStore.php
src/store/tests/InMemoryStoreTest.php

Hi 👋🏻 
This PR aim to introduce an `InMemoryStore` to store vectors (mostly used for tests environments and/or POCs), the implementation is based around `cosine` similarity (others search algorithms can be used but will requires a dedicated interface like `SearchStrategyInterface` or other).
This store also allows to retrieve only a specific amount of items if required.
This store don't use `initialize` as everything is stored in an array.
PS: An optimized approach would be to use `fpow` but it requires `8.4` so ... Well, maybe for later 😄

[Store] Add InMemory

---

examples/misc/chat-with-memory.php
examples/store/mariadb-chat-memory.php
src/agent/doc/index.rst
src/agent/src/Memory/EmbeddingProvider.php
src/agent/src/Memory/Memory.php
src/agent/src/Memory/MemoryInputProcessor.php
src/agent/src/Memory/MemoryProviderInterface.php
src/agent/src/Memory/StaticMemoryProvider.php
src/agent/tests/Memory/EmbeddingProviderTest.php
src/agent/tests/Memory/MemoryInputProcessorTest.php
src/agent/tests/Memory/StaticMemoryProviderTest.php

| Issues        |  
See original contribution at https://github.com/php-llm/llm-chain/pull/387
> This PR introduces a flexible memory system that allows the LLM to recall contextual information that are permantent for the conversation. In difference to tools it can be always utilized, when use_memory option is not disabled. It would be possible to fetch memory by a tool with a system instruction like always call the tool foo_bar but, for me, this feels like a bad design to always force the model to do a tool call without further need.
>
> Currently i have added just two memory providers to show what my idea is. I could also think about a write layer to fill a …

[Agent] Add basic setup for memory injections to system prompt

---

.phpstan/ForbidNativeExceptionRule.php
.phpstan/extension.neon
src/agent/composer.json
src/agent/phpstan.dist.neon
src/agent/src/Chat/MessageStore/CacheStore.php
src/agent/src/Chat/MessageStore/SessionStore.php
src/ai-bundle/composer.json
src/ai-bundle/phpstan.dist.neon
src/ai-bundle/src/AIBundle.php
src/ai-bundle/src/Exception/ExceptionInterface.php
src/ai-bundle/src/Exception/InvalidArgumentException.php
src/mcp-bundle/composer.json
src/mcp-bundle/phpstan.dist.neon
src/mcp-sdk/composer.json
src/mcp-sdk/phpstan.dist.neon
src/mcp-sdk/src/Exception/InvalidArgumentException.php
src/mcp-sdk/src/Server/RequestHandler/PromptGetHandler.php
src/mcp-sdk/src/Server/RequestHandler/ToolCallHandler.php
src/platform/composer.json
src/platform/phpstan.dist.neon
src/platform/src/Bridge/Bedrock/Meta/LlamaModelClient.php
src/platform/src/Bridge/Bedrock/PlatformFactory.php
src/store/composer.json
src/store/phpstan.dist.neon
src/store/src/Bridge/ChromaDB/Store.php
src/store/src/Bridge/MariaDB/Store.php
src/store/src/Bridge/MongoDB/Store.php
src/store/src/Bridge/Pinecone/Store.php

This is only a POC by Claude, but wanted to check how easy it is since I'm already catching this as recurring pattern while reviewing incoming PRs.
WDYT?

Add PHPStan rule forbidding native exceptions and switch remaining ones

---

examples/store/memory-similarity-search.php
src/store/src/Bridge/Meilisearch/Store.php
src/store/tests/Bridge/Meilisearch/StoreTest.php

Metadata should only include additional but relevant information. It is handed over by the SimilaritySearch to the LLM and too much unnecessary information hurt the context size and token consumption.
On top, score was not set.

[Store][Meilisearch] Remove id, score and vectors from metadata

---

src/platform/CHANGELOG.md

- Added Albert API to the platform CHANGELOG as it was missing from PR #140
This PR adds the changelog entry for the Albert API support that was merged in #140. The Albert API is a French sovereign AI gateway that provides OpenAI-compatible endpoints while ensuring data remains within French/EU jurisdiction.
- Original PR: #140

[Platform] Add Albert API to platform CHANGELOG

---

src/ai-bundle/src/Profiler/DataCollector.php
src/ai-bundle/src/Profiler/TraceablePlatform.php
src/ai-bundle/tests/Profiler/DataCollectorTest.php

| Issues        | Fix #161
Address 2 streaming-related issues:
1. When using `symfony/ai` from within `StreamedResponse` callback (in http controller), no data was collected due to not implementing `LateDataCollectorInterface`
2. An attempt to save `StreamResult` to the profiler storage always failed, because `\Generator`s are not serializable
Both are used in the Turbo Stream Bot demo, and now the profiler works. Though the toolbar still does not auto-update, but that is currently expected behavior.

[AIBundle] Fix stream result profiling

---

src/mcp-sdk/src/Server/RequestHandler/PromptListHandler.php
src/mcp-sdk/src/Server/RequestHandler/ResourceListHandler.php
src/mcp-sdk/src/Server/RequestHandler/ToolListHandler.php
src/mcp-sdk/tests/Server/RequestHandler/PromptListHandlerTest.php
src/mcp-sdk/tests/Server/RequestHandler/ResourceListHandlerTest.php

| Issues        | N/A
Use foreach instead of array_map because array_map does not accept generators and add test coverage.

[MCP SDK] Use foreach instead of `array_map` because `array_map` does not accept generators

---

src/ai-bundle/config/options.php
src/ai-bundle/config/services.php
src/ai-bundle/src/AIBundle.php
src/ai-bundle/src/Profiler/DataCollector.php

| Issues        | Related to #90
Don't autowire or autoconfigure anything in AI Bundle

[AIBundle] Wire & configure services explicitly

---

src/ai-bundle/config/services.php
src/ai-bundle/src/AIBundle.php

Fix DI config after #163 / #154. Should've rebased before merge – now we're getting a bunch of errors on `main`:
```
Symfony\AI\Agent\Toolbox\Toolbox::__construct(): Argument #1 ($tools) must be of type Traversable|array, Symfony\AI\Agent\Toolbox\ToolFactory\ReflectionToolFactory given
```
etc

[AIBundle] Fix dependency injection

---

src/agent/src/AgentInterface.php
src/agent/src/ChatInterface.php

| Issues        | Fix #...
Hi @chr-hertel, this lib seems to lack of `@throws` phpdoc.
For static analysis usage (and developer experience) it seems better to tell which methods are throwing exceptions.
I didn't look for every methods but started with two important methods imho.

[Agent] Add `@throws` tag

---

src/store/tests/Bridge/MariaDB/StoreTest.php

| Issues        | Refs #189 
This commit adds comprehensive unit tests for the MariaDB Store query method, specifically testing the fix from PR #189 where sprintf placeholders weren't being properly replaced in the WHERE clause when using minScore parameter.
Tests cover:
- Query with minScore parameter (validates the bug fix)
- Query without minScore parameter
- Query with custom limit option

[Store][MariaDB] Add unit tests for query method

---

src/platform/doc/index.rst

| Issues        | Fix
This is not a bug fix or feature, I noticed the error while trying to work with the package. I fixed a typographical error in the documentation. The static method "ofSystem" does not exist on the Symfony\AI\Platform\Message class, it should be "forSystem".

Fixed Typo Error on Platform documentation

---

src/platform/CHANGELOG.md
src/platform/doc/index.rst
src/platform/src/InMemoryPlatform.php
src/platform/src/Result/InMemoryRawResult.php
src/platform/tests/InMemoryPlatformTest.php

| Bug fix?      |no
| Docs?         | yes 
| Issues        | none 
This PR adds two test-friendly classes to the Symfony AI Platform component:
The `InMemoryPlatform` is a test-specific implementation of `PlatformInterface` that returns a `TextResult` wrapped in a `ResultPromise`.
It supports:
- A fixed string response (e.g. `'Fake reply'`)
- A callable response based on the `Model`, `input`, and `options`
This makes it ideal for unit or integration tests, or even functional tests where a full AI stack is not needed.
The `InMemoryRawResult` implements `RawResultInterface` and is used internally by `InMemoryPlatform`. It wraps:
- A structured array (`getData()`)
- A generic object (`getObject()`)
to …

[Platform] Add `InMemoryPlatform` and `InMemoryRawResult` for testing

---

demo/composer.json

| Issues        | n/a
As we're using unbounded deps for now (`@dev`), we cannot use `--strict` on `composer validate`.

[Demo] Remove --strict to composer validate (using @dev for now on deps)

---

src/mcp-bundle/phpstan.dist.neon
src/mcp-bundle/tests/DependencyInjection/McpBundleTest.php

This commit adds comprehensive tests for the McpBundle configuration:
- Tests default configuration values
- Tests custom configuration for app name and version
- Tests client transport configurations (stdio and sse)
- Tests service registration based on transport settings
- Tests autoconfiguration of MCP interfaces

[MCP Bundle] Add test case for configuration

---

examples/ollama/toolcall.php
src/platform/CHANGELOG.md
src/platform/src/Bridge/Ollama/Contract/AssistantMessageNormalizer.php
src/platform/src/Bridge/Ollama/Contract/OllamaContract.php
src/platform/src/Bridge/Ollama/Ollama.php
src/platform/src/Bridge/Ollama/OllamaModelClient.php
src/platform/src/Bridge/Ollama/OllamaResultConverter.php
src/platform/src/Bridge/Ollama/PlatformFactory.php
src/platform/tests/Bridge/Ollama/Contract/AssistantMessageNormalizerTest.php
src/platform/tests/Bridge/Ollama/OllamaResultConverterTest.php
src/platform/tests/Bridge/Ollama/OllamaTest.php

| New feature?  | yes?
Running a toolbox agent with ollama was not yet supported. This ensures, that tool messages and responses work with a locally hosted ollama instance. It seems not to be a fix as it was not meant to work and it is not really a mentionable feature as one could expect it to work like the others so I am not really sure to work where to add more content for humans. I tested it with the given new example in `examples/ollama/toolcall.php`.
A current design decision had me struggling a bit. I was not yet able to solve in a good way the fact, that ollama itself cannot claim every model to have tool support. So someone who uses a model needs to know before its usage …

[Platform] Add tooling support for ollama to allow agent and toolbox usage

---

src/ai-bundle/src/AiBundle.php

For Whisper support on Azure we also need the OpenAI contract instead of the default one.

[AI Bundle] Change Azure Contract to OpenAI for Whisper support

---

.github/workflows/code-quality.yaml
.github/workflows/unit-tests.yaml

| Issues        | -
For the phpstan job, we don't need any matrix. We only care about what phpstan can report with latest deps.
For the phpunit ones, we should always test with dev dependencies, like we're doing on symfony/symfony.
https://github.com/symfony/ai/pull/237/files?w=1

Simply code-quality matrix

---

demo/src/MCP/Tools/CurrentTimeTool.php
src/mcp-sdk/examples/cli/src/ExampleTool.php
src/mcp-sdk/src/Capability/Tool/IdentifierInterface.php
src/mcp-sdk/src/Capability/Tool/MetadataInterface.php
src/mcp-sdk/src/Capability/Tool/ToolAnnotationsInterface.php
src/mcp-sdk/src/Server/RequestHandler/ToolListHandler.php
src/mcp-sdk/tests/Server/RequestHandler/ToolListHandlerTest.php

The current Tool definition lacks a few fields, this PR covers it.

[MCP SDK] Update Tool schema to match 2025-06-18 and introduce `ToolAnnotationsInterface`

---

src/mcp-bundle/tests/DependencyInjection/McpBundleTest.php

This adds tests for the pagination functionality that was introduced in PR #227.

[MCP Bundle] Add tests for `mcp.page_size` parameter

---

src/store/src/Bridge/Postgres/Store.php

| Issues        |
I want to be able to filter some record before comparison.
Usage:
```php
$crawlAId = '013e951c-335f-4e2b-9414-9eedbf0f51df';
$crawlBId = '396af6fe-0dfd-47ed-b222-3dbcced3f38e';
$rows = $connection
->executeQuery(<<<SQL
SELECT *
FROM {$tableName}
WHERE metadata->>'crawlId' = '{$crawlAId}'
SQL)
->fetchAllAssociative()
;
foreach ($rows as $i => $row) {
$vector = new Vector(json_decode($row['embedding'], true));
$documents = $store->query(
$vector,
[
'maxScore' => 0.1,
'where' => "metadata->>'crawlId' = :crawlId AND id != :currentId",
'params' => [
'crawlId' => $crawlBId,
'currentId' => $row['id'],
],
],
);
if (!$documents) {
continue;
}
$metadata = …
```

[Store][Pg] Add support for custom "where" expression

---

src/ai-bundle/src/AiBundle.php
src/ai-bundle/tests/DependencyInjection/AiBundleTest.php

| Issues        | Fix https://github.com/php-llm/llm-chain-bundle/issues/102
Fault tolerant toolbox was never registered if you used `tools: true` instead of defining tools explicitly.

[AiBundle] Register fault tolerant default toolbox

---

examples/gemini/server-tools.php

Fix the Gemini server-tools example to make use of the created `AgentProcessor` in the `Agent`.

[Examples] Fix gemini server-tools example to actually use AgentProcessor

---

src/ai-bundle/config/options.php
src/ai-bundle/src/AiBundle.php
src/ai-bundle/tests/DependencyInjection/AiBundleTest.php

| Issues        | #260 
Hi 👋🏻 
A small fix for the meilisearch store, the endpoint was not sent, tests fixed.

[AIBundle] fix missing endpoint for Meilisearch store

---

src/platform/src/Bridge/Ollama/Contract/AssistantMessageNormalizer.php
src/platform/tests/Bridge/Ollama/Contract/AssistantMessageNormalizerTest.php

| New feature?  |no
The assistant message for ollama chats supports `content` as well as `tool_calls`. Not providing content to assistant messages leads to loss of context especially in cases where no tools have been used.

[Platform] Add content when normalizing  ollama assistant messages

---

src/ai-bundle/src/AiBundle.php
src/ai-bundle/tests/DependencyInjection/AiBundleTest.php

Hi 👋🏻 
This PR aims to add "injection aliases", those allows the user to use the following code while defining X agents: 
```php
public function __construct(
private AgentInterface $fooAgent,
) {
}
```
Why the `Agent` suffix? Because we don't know, maybe one day, a service will be called `foo` and it will trigger an error, it seems better to define a suffix and ensure that this bundle is the only one to use it.

[AIBundle] Improve injection aliases

---

src/platform/src/Bridge/OpenAi/Gpt.php

The new GPT Models are out, so i have added them to the platform with default configuration for image support and structured output. 
https://platform.openai.com/docs/models/gpt-5
https://platform.openai.com/docs/models/gpt-5-mini
https://platform.openai.com/docs/models/gpt-5-nano
https://platform.openai.com/docs/models/gpt-5-chat-latest

[OpenAI] Add GPT 5 Models

---

src/store/src/Bridge/Qdrant/Store.php

Using the function as-is provided the data, all with a score of 0. Passing the vector correctly, I was able to get results with scoring as expected.
Ref: https://qdrant.tech/documentation/concepts/search/

[Store][Qdrant] Use the correct key for making a query

---

src/store/src/Bridge/ChromaDb/Store.php
src/store/src/Document/Loader/TextFileLoader.php
src/store/src/Document/Metadata.php
src/store/src/Document/Transformer/TextSplitTransformer.php
src/store/tests/Bridge/ChromaDb/StoreTest.php
src/store/tests/Document/Loader/TextFileLoaderTest.php
src/store/tests/Document/MetadataTest.php
src/store/tests/Document/Transformer/TextSplitTransformerTest.php

| Docs?         | yes 
| Issues        | N/A
This is just a draft for now to explain what I am trying to achieve - I would like to be able to store the original document content in the Chroma DB records, but the `VectorDocument` currently has no way to pass that in, other than the metadata. I feel like this requirement will not be specific just to Chroma DB, but various databases used for embeddings will support storing of the original document content along with the vectors.
Any suggestions on how to approach this holistically? Should the `VectorDocument` be expanded with optional field like `?string $content = null`?
Additionally (see https://symfony.com/releases):
- Always add …

[Store] Add a way to store document content when using Chroma DB

---

src/mcp-sdk/src/Server/RequestHandler/PromptGetHandler.php
src/mcp-sdk/src/Server/RequestHandler/ToolCallHandler.php
src/platform/src/Bridge/HuggingFace/ResultConverter.php
src/platform/src/Bridge/Mistral/Embeddings/ResultConverter.php
src/platform/src/Bridge/Mistral/Llm/ResultConverter.php
src/platform/src/Vector/Vector.php
src/store/src/Bridge/ClickHouse/Store.php
src/store/tests/Bridge/ClickHouse/StoreTest.php

Replace string concatenation and interpolation with sprintf in all exception messages for consistency and better formatting.

 Fix exceptions to use `sprintf` for string formatting

---

src/ai-bundle/src/AiBundle.php
src/ai-bundle/tests/DependencyInjection/AiBundleTest.php

This allows an easier manipulation of all agents with a CompilerPass and findTaggedServiceIds.
This also allow to inject all agents with `AutowireIterator`.

 Add tag for every agents

---

src/agent/src/Agent.php
src/agent/tests/AgentTest.php

Similar to https://github.com/symfony/ai/issues/344 @OskarStark 
Do you think it could be ok to expose the Agent model ?
It would be useful to access data like model name for logging purpose (without the need for reflection class).
But I'm dunno if it should be in the AgentInterface, your call.

[Agent] Expose Agent model

---

src/store/src/Bridge/ClickHouse/Store.php

[Store][ClickHouse] Make store `final readonly`

---

.github/workflows/code-quality.yaml
.github/workflows/doctor-rst.yaml
.github/workflows/unit-tests.yaml

Update all workflow files to use actions/checkout@v5 instead of v4

 Update GitHub Actions checkout to v5

---

examples/ollama/stream.php
src/platform/CHANGELOG.md
src/platform/src/Bridge/Ollama/OllamaMessageChunk.php
src/platform/src/Bridge/Ollama/OllamaResultConverter.php
src/platform/tests/Bridge/Ollama/OllamaClientTest.php

| Docs?         | yes/no
| Issues        | Fix #338
Both a bug fix and a feature?  Support streaming output from Ollama, preventing an error being thrown if streaming output is sent with the chat request.

[Platform][Ollama] Support streaming output

---

src/platform/src/Bridge/Voyage/ResultConverter.php
src/platform/tests/Bridge/Voyage/ResultConverterTest.php

When indexing multiple documents, only the first vector was returned, leading to an undefined array key error

[Platform][Voyage] Include all returned vectors rather than just the first

---

examples/elevenlabs/text-to-speech-as-stream.php
src/platform/src/Bridge/ElevenLabs/ElevenLabsClient.php
src/platform/src/Bridge/ElevenLabs/ElevenLabsResultConverter.php
src/platform/src/Bridge/ElevenLabs/PlatformFactory.php
src/platform/tests/Bridge/ElevenLabs/ElevenLabsClientTest.php
src/platform/tests/Bridge/ElevenLabs/ElevenLabsConverterTest.php

Hi 👋🏻 
This PR aim to introduce the support for streaming TTS.

[Platform] Add stream for ElevenLabs TTS

---

examples/compose.yaml

[Examples] Add `ChromaDB` to `compose.yaml`

---

src/ai-bundle/src/AiBundle.php
src/platform/src/Bridge/Anthropic/ModelClient.php
src/platform/src/Bridge/Anthropic/PlatformFactory.php
src/platform/tests/Bridge/Anthropic/ModelClientTest.php

[AI Bundle][Platform] Fix Anthropic platform definition

---

examples/vertexai/server-tools.php
src/platform/doc/vertexai-server-tools.rst
src/platform/src/Bridge/VertexAi/Gemini/ModelClient.php
src/platform/tests/Bridge/VertexAi/Gemini/ModelClientTest.php

| Issues        | Fix #386
1. Align "Gemini via VertexAI" server tools configuration with Gemini platform
- This makes it easier to migrate from Gemini -> Vertex and vice-versa 
3. Fix the server tools example to actually use server tools
4. Fix how server tools are provided to VertexAI
Worth noting that unlike Gemini API, it seems VertexAI does not support client-side tools when using server-side tools, the api is returning `Multiple tools are supported only when they are all search tools`. This is why the `Clock` & `Toolbox` was removed from the example.

[Platform] Fix VertexAI server tools

---

src/platform/src/Bridge/OpenAi/Contract/FileNormalizer.php

[Platform] Fix doc type on FileNormalizer

---

src/ai-bundle/config/services.php

Christopher, I think we need to register the normalizer contract so that it’s available when using the Symfony bundle.

[AI Bundle][OpenAI] Register normalizer contract

---

examples/.env
examples/rag/clickhouse.php

| Issues        | Fix none
Hi 👋🏻 
Here's the rag example for `Clickhouse` as discussed in #335

[Examples][ClickHouse] Add RAG example

---

src/platform/src/Bridge/Albert/PlatformFactory.php
src/platform/src/Bridge/Azure/OpenAi/EmbeddingsModelClient.php
src/platform/src/Bridge/Azure/OpenAi/GptModelClient.php
src/platform/src/Bridge/Azure/OpenAi/WhisperModelClient.php
src/platform/src/Bridge/OpenAi/DallE/Base64Image.php
src/platform/src/Bridge/OpenAi/DallE/ModelClient.php
src/platform/src/Bridge/OpenAi/DallE/UrlImage.php
src/platform/src/Bridge/OpenAi/Embeddings/ModelClient.php
src/platform/src/Bridge/OpenAi/Gpt/ModelClient.php
src/platform/src/Bridge/OpenAi/Whisper/ModelClient.php
src/platform/src/Bridge/OpenRouter/ModelClient.php
src/platform/src/Bridge/Replicate/LlamaModelClient.php
src/platform/src/Contract/JsonSchema/Attribute/With.php
src/store/src/Document/TextDocument.php

Replace all short-circuit evaluation patterns (`|| throw`) with classic if statements for better readability and consistency across the codebase. AFAIK this is more the Symfony-way of doing.

[Platform][Store] Refactor short-circuit evaluation to classic if statements

---

src/platform/src/Bridge/Gemini/Embeddings.php

| Issues        | Follows #359 
cc @natewiebe13

[Platform][Gemini][Embeddings] Remove comments for dimensions

---

demo/tests/SmokeTest.php
src/agent/tests/Toolbox/MetadataFactory/ReflectionFactoryTest.php
src/platform/tests/Bridge/VertexAi/Gemini/ModelClientTest.php
src/platform/tests/Message/AssistantMessageTest.php
src/platform/tests/Message/SystemMessageTest.php
src/platform/tests/Message/ToolCallMessageTest.php
src/platform/tests/Message/UserMessageTest.php

Following the codebase convention to use $this->assert* instead of self::assert* for better consistency across all test files

[Agent][Demo][Platform] Replace `self::assert*` with `$this->assert*` in test files

---

src/ai-bundle/composer.json
src/ai-bundle/config/services.php
src/ai-bundle/src/AiBundle.php
src/ai-bundle/src/Command/ChatCommand.php
src/ai-bundle/src/Exception/RuntimeException.php
src/ai-bundle/tests/Command/ChatCommandTest.php

Implement a new console command `bin/console ai:chat` that allows users to interactively chat with different AI agents (blog, stream, youtube, wikipedia, audio). The command supports custom system prompts and maintains conversation history.

[AI Bundle] Add chat console command for interactive AI agent conversations

---

src/ai-bundle/src/Command/ChatCommand.php

| Issues        | Follows #395 
cc @stof

[AI Bundle] Improve `ChatCommand`

---

CLAUDE.md

 Add `CLAUDE.md` file

---

src/store/tests/Document/VectorizerTest.php

[Store] Add comprehensive unit tests for `Vectorizer`

---

src/platform/tests/Bridge/Bedrock/Anthropic/ClaudeResultConverterTest.php
src/platform/tests/Bridge/Bedrock/Meta/LlamaResultConverterTest.php
src/platform/tests/Bridge/Bedrock/Nova/NovaResultConverterTest.php

[Platform][Bedrock] Add tests for result converters

---

src/platform/tests/Bridge/HuggingFace/ApiClientTest.php
src/platform/tests/Bridge/HuggingFace/PlatformFactoryTest.php
src/platform/tests/Bridge/HuggingFace/ResultConverterTest.php

[Platform][HuggingFace] Add tests for Bridge components

---

demo/composer.json
examples/composer.json
src/agent/composer.json
src/ai-bundle/composer.json
src/platform/composer.json
src/store/composer.json

 Run `composer normalize`

---

fixtures/Bridge/Gemini/code_execution_outcome_deadline_exceeded.json
fixtures/Bridge/Gemini/code_execution_outcome_failed.json
fixtures/Bridge/Gemini/code_execution_outcome_ok.json
src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php
src/platform/tests/Bridge/Gemini/CodeExecution/ResultConverterTest.php

| Issues        | Fix #422
This PR fixes a crash in the **Gemini** ResultConverter when handling responses that only contained executableCode and codeExecutionResult parts.
Before: 
- RuntimeException: Unsupported finish reason "STOP"
After:
- Proper conversion into a TextResult containing formatted code blocks and the last successful OUTCOME_OK output.
- No more exceptions for valid Gemini responses.
What’s Changed
- Enhanced choice conversion logic in ResultConverter::convertChoice():
- Single part → keep legacy behavior (functionCall, text, or one code/output part).
- Multiple parts → aggregate:
- executableCode → Markdown code blocks.
- codeExecutionResult …

[Platform][Gemini] Fix choice conversion logic for `executableCode` and `codeExecutionResult`

---

fixtures/Bridge/VertexAi/code_execution_outcome_deadline_exceeded.json
fixtures/Bridge/VertexAi/code_execution_outcome_failed.json
fixtures/Bridge/VertexAi/code_execution_outcome_ok.json
src/platform/src/Bridge/VertexAi/Gemini/ResultConverter.php
src/platform/tests/Bridge/VertexAi/Gemini/ResultConverterTest.php

Same as #421 but for VertexAI bridge
This PR fixes a crash in the Gemini ResultConverter when handling responses that only contained executableCode and codeExecutionResult parts.
Rather than duplicating the code, I created a trait that is used in both bridges.
I also reused the same test fixtures.

[Platform][VertexAI] Update `ResultConverter`

---

src/store/src/Document/Vectorizer.php
src/store/src/Document/VectorizerInterface.php

[Store] Move class comment from `Vectorizer` to `VectorizerInterface`

---

src/store/src/Indexer.php

The comment was already present on `IndexerInterface` and duplicated on the implementation class.

[Store] Remove duplicate class comment from `Indexer`

---

src/store/src/Bridge/Qdrant/Store.php
src/store/tests/Bridge/Qdrant/StoreTest.php

Allow setting filters on queries

[Store][Qdrant] Allow setting filters on a query

---

src/store/src/Document/Loader/TextFileLoader.php
src/store/src/Document/LoaderInterface.php
src/store/src/Document/Transformer/ChainTransformer.php
src/store/src/Document/Transformer/ChunkDelayTransformer.php
src/store/src/Document/Transformer/TextSplitTransformer.php
src/store/src/Document/TransformerInterface.php
src/store/src/Document/Vectorizer.php
src/store/src/Document/VectorizerInterface.php
src/store/src/Indexer.php
src/store/tests/Document/Loader/TextFileLoaderTest.php
src/store/tests/Document/Transformer/ChainTransformerTest.php
src/store/tests/Document/Transformer/ChunkDelayTransformerTest.php
src/store/tests/Document/Transformer/TextSplitTransformerTest.php
src/store/tests/Document/VectorizerTest.php

Discussed with @chr-hertel upfront.
Replace generic `__invoke` methods with descriptive names:
- `TransformerInterface::__invoke` → `transform`
- `VectorizerInterface::__invoke` → `vectorize`
- `LoaderInterface::__invoke` → `load`
This improves code readability and makes the intent of each interface clearer. Updated all implementations and usages throughout the codebase.

[Store] Rename `__invoke` methods in interfaces to descriptive names

---

src/store/src/Document/Loader/InMemoryLoader.php

[Store] Add documentation to `InMemoryLoader` class

---

demo/src/Blog/Command/EmbedCommand.php
demo/src/Blog/Command/QueryCommand.php

Convert `EmbedCommand` and `QueryCommand` to use Symfony 7.3's invokable commands feature by removing `Command` inheritance and using `__invoke` method instead of `execute()`.

[Demo] Convert blog commands to invokable commands

---

src/platform/src/Bridge/Mistral/Mistral.php

| New feature?  | Yes
This pull request extends the Mistral integration to add support for the `VOXTRAL` models, which are specialized for processing audio data. This enables the transcription of audio files through the Mistral platform.
**Key Changes:**
*   **New Model Constants:** In the `Mistral` class, the constants `VOXTRAL_SMALL` and `VOXTRAL_MINI` have been added.
*   **Audio Capability:** The `Capability::INPUT_AUDIO` is now correctly assigned to the models when one of the VOXTRAL models is selected.
*   **Usage Example:** A new `ai:mistral` command has been created to demonstrate the functionality. It shows how to send an audio file (`audio.mp3`) to the …

[Platform][Mistral] Add support for Voxtral models with audio input and tool-calling

---

demo/tests/Blog/ChatTest.php
src/agent/doc/index.rst
src/agent/src/Exception/OutOfBoundsException.php
src/agent/src/MockAgent.php
src/agent/src/MockResponse.php
src/agent/tests/MockAgentTest.php
src/agent/tests/MockResponseTest.php

Implements `MockAgent` and `MockResponse` classes for testing purposes. Similar to Symfony's `MockHttpClient`, this provides predictable responses without making external API calls and includes assertion methods for verifying interactions.
- **Predictable Responses**: Configure specific responses for expected inputs
- **Call Tracking**: Track all agent calls with detailed information
- **Assertion Methods**: Verify agent interactions in tests
- **MockResponse Objects**: Use response objects for the MockAgent
- **Callable Responses**: Dynamic responses based on input and context
```php
use Symfony\AI\Agent\MockAgent;
use …
```

[Agent] Add `MockAgent` for testing purposes

---

demo/config/packages/ai.yaml
src/ai-bundle/config/options.php
src/ai-bundle/doc/index.rst
src/ai-bundle/src/AiBundle.php
src/ai-bundle/tests/DependencyInjection/AiBundleTest.php

| Q | A |
|---|---|
| Bug fix? | no |
| New feature? | yes |
| Docs? | yes |
| Issues | Eases implementation of [#514](https://github.com/symfony/ai/pull/514) |
| License | MIT |
Restructures `system_prompt` configuration to nest `include_tools` for better organization and ergonomics.
- Move `include_tools` from agent level to `system_prompt` level
- Support both string (simple) and array (advanced) formats
```yaml
system_prompt: 'You are helpful.'
include_tools: true
```
```yaml
system_prompt: 'You are helpful.'
```
```yaml
system_prompt:
prompt: 'You are helpful.'
include_tools: true
```

[AI Bundle] Restructure `system_prompt` configuration to nest `include_tools`

---

demo/config/packages/ai.yaml
src/ai-bundle/config/options.php
src/ai-bundle/doc/index.rst
src/ai-bundle/src/AiBundle.php
src/ai-bundle/tests/DependencyInjection/AiBundleTest.php

| Issues        | Follows #576 
- Renamed system_prompt configuration key to prompt for clearer naming
- Renamed nested 'prompt' key to 'text' in array configuration to avoid confusion
- Updated all configuration examples in demo
- Updated documentation with new configuration structure
- Updated all tests to use new configuration structure
- Maintained backward compatibility through configuration normalization
I prefer `text`, as this way, we can introduce `file` and validate that only one can be set. I am planning to support twig and json prompts in the future.

[AI Bundle] Rename `system_prompt` to `prompt` and `prompt` key to `text`

---

src/platform/src/Bridge/Anthropic/ResultConverter.php
src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php
src/platform/src/Bridge/OpenAi/Gpt/ResultConverter.php
src/platform/src/Exception/RateLimitExceededException.php
src/platform/tests/Bridge/Anthropic/ResultConverterRateLimitTest.php
src/platform/tests/Bridge/Gemini/Gemini/ResultConverterRateLimitTest.php
src/platform/tests/Bridge/OpenAi/Gpt/ResultConverterRateLimitTest.php

| Bug fix?      |no
| New feature?  |no 
| Issues        | #528 
- Created a `RateLimitExceededException` to handle 429 across all AI platforms
- Unified the handling of rate limit responses with platform-specific retry information
- Used platform-specific header extraction for each provider:
- Anthropic: Standard retry-after HTTP header (seconds)
- Gemini: No retry information provided
- OpenAI: Custom headers x-ratelimit-reset-requests and x-ratelimit-reset-tokens

[Platform] Implement `RateLimitExceededException` handling across AI platforms

---

src/agent/src/Memory/MemoryInputProcessor.php
src/agent/tests/Memory/MemoryInputProcessorTest.php

| Issues        | Follows #580
- Memory content now appears first (from my POV it is best practice), followed by system prompt
- Added `# System Prompt` headline separator between sections
cc @DZunke fyi, as you provided this feature

[Agent] Reorder memory and system prompt

---

src/ai-bundle/config/options.php

[AI Bundle] Correct exception message to mention both `text` and `include_tools`

---

src/agent/src/Memory/EmbeddingProvider.php
src/agent/src/Memory/MemoryInputProcessor.php
src/agent/src/Memory/MemoryProviderInterface.php
src/agent/src/Memory/StaticMemoryProvider.php
src/agent/tests/Memory/EmbeddingProviderTest.php
src/agent/tests/Memory/MemoryInputProcessorTest.php
src/agent/tests/Memory/StaticMemoryProviderTest.php

Simplify the method name by removing the redundant 'Memory' prefix. This improves readability and follows interface naming conventions.

[Agent] Rename `MemoryProviderInterface::loadMemory` to `load`

---

src/ai-bundle/config/options.php
src/ai-bundle/src/AiBundle.php

Move validation that checks if model classes extend Symfony\AI\Platform\Model from runtime (in AiBundle.php) to configuration validation (in options.php).
This provides earlier validation during config processing, better error reporting, and cleaner bundle code.

[AI Bundle] Move model class validation to configuration layer

---

src/ai-bundle/config/options.php
src/ai-bundle/doc/index.rst
src/ai-bundle/src/AiBundle.php
src/ai-bundle/tests/DependencyInjection/AiBundleTest.php

| Issues        | Fix #591 
Remove guessing logic for memory keys and introduce explicit syntax:
```yaml
memory: 'text' # always creates static memory processor
```
```yaml
memory:
service: 'service_name' # uses service reference
```
This makes the configuration more predictable and eliminates the need to check if a string refers to an existing service.
cc @DZunke

[AI Bundle] Simplify memory configuration structure

---

src/ai-bundle/src/AiBundle.php

This looks wrong to me.
Follows https://github.com/symfony/ai/pull/604#discussion_r2353650017

[AI Bundle][Ollama] Fix duplicate `setFactory` call for platform

---

examples/.env
examples/ollama/README.md
examples/ollama/chat-llama.php
examples/ollama/embeddings.php
examples/ollama/indexer.php
examples/ollama/rag.php
examples/ollama/stream.php
examples/ollama/structured-output-math.php
examples/ollama/toolcall.php

[Examples] Consistency about Ollama model config via env, and wrap up docs

---

.github/workflows/integration-tests.yaml

Replace manual composer caching with ramsey/composer-install@v3 which provides better caching and more reliable dependency management for both examples and demo jobs.

[Demo][CI] Use `ramsey/composer-install`

---

demo/src/Blog/Command/QueryCommand.php

| Issues        | Replaces #619 
Replace direct platform usage with `VectorizerInterface` injection using the `#[Autowire]` attribute for cleaner dependency management and better separation of concerns.

[Demo] Leverage `Vectorizer` in `QueryCommand`

---

examples/composer.json

Adds minimum-stability configuration to allow dev dependencies and development versions of packages in examples.
Needed for #277, thanks @xabbuh

[Examples] Add `minimum-stability` `dev` to `composer.json`

---

composer.json
examples/composer.json
src/mcp-bundle/composer.json
src/mcp-sdk/composer.json
src/mcp-sdk/examples/cli/composer.json

Ran composer normalize on all composer.json files to ensure consistent formatting and ordering of dependencies.

 Normalize `composer.json` files

---

.github/workflows/integration-tests.yaml
.github/workflows/unit-tests.yaml
composer.json
examples/commands/stores.php
examples/composer.json
src/agent/composer.json
src/agent/tests/Toolbox/Tool/BraveTest.php
src/agent/tests/Toolbox/Tool/FirecrawlTest.php
src/agent/tests/Toolbox/Tool/MapboxTest.php
src/agent/tests/Toolbox/Tool/OpenMeteoTest.php
src/agent/tests/Toolbox/Tool/WikipediaTest.php
src/ai-bundle/composer.json
src/ai-bundle/src/AiBundle.php
src/ai-bundle/tests/Command/ChatCommandTest.php
src/mcp-bundle/composer.json
src/mcp-sdk/composer.json
src/mcp-sdk/examples/cli/composer.json
src/platform/composer.json
src/platform/src/Bridge/Anthropic/ResultConverter.php
src/platform/src/Bridge/Mistral/Llm/ResultConverter.php
src/platform/src/Bridge/OpenAi/Gpt/ResultConverter.php
src/platform/src/Bridge/Perplexity/ResultConverter.php
src/store/composer.json
src/store/tests/Document/Loader/RssFeedLoaderTest.php

- Update all composer.json files to require Symfony ^7.3|^8.0
- Minimum supported version is now Symfony 7.3 LTS
Needs

 Drop Symfony 6.4 support, require ^7.3|^8.0

---

src/platform/tests/Bridge/DockerModelRunner/Completions/ResultConverterTest.php
src/platform/tests/Bridge/DockerModelRunner/Embeddings/ResultConverterTest.php

| Issues        | Follows #628 
Tests verify that ModelNotFoundException is properly thrown when:
- 404 response contains "model not found" message (case-insensitive)
- Exception is not thrown for 404 responses without the specific message
cc @welcoMattic

[Platform][DockerModelRunner] Add tests for `ModelNotFoundException`

---

examples/memory/mariadb.php

The 'embedding' value is the default for vectorFieldName parameter, so it can be omitted to simplify the example code.

 Remove redundant `vectorFieldName` parameter from MariaDB example

---

src/agent/src/Toolbox/Tool/Clock.php
src/agent/tests/Toolbox/Tool/ClockTest.php

[Agent] Support setting timezone on clock tool

---

src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php
src/platform/src/Bridge/VertexAi/Gemini/ResultConverter.php

Remove unnecessary 0 code parameter and use named 'previous' argument for better code readability in RuntimeException constructors.

[Agent] Use named arguments for exception previous parameter

---

.phpstan/ForbidTestCoverageAttributesRule.php
.phpstan/extension.neon
src/mcp-sdk/tests/Message/ErrorTest.php
src/mcp-sdk/tests/Message/FactoryTest.php
src/mcp-sdk/tests/Message/ResponseTest.php
src/mcp-sdk/tests/Server/JsonRpcHandlerTest.php
src/mcp-sdk/tests/Server/RequestHandler/PromptListHandlerTest.php
src/mcp-sdk/tests/Server/RequestHandler/ResourceListHandlerTest.php
src/mcp-sdk/tests/Server/RequestHandler/ToolListHandlerTest.php
src/mcp-sdk/tests/ServerTest.php
src/platform/tests/Bridge/OpenAi/DallE/Base64ImageTest.php
src/platform/tests/Bridge/OpenAi/DallE/ImageResultTest.php
src/platform/tests/Bridge/OpenAi/DallE/ResultConverterTest.php

| Issues        | Follows #647
This rule prevents the use of Large, Small, Medium, CoversClass and UsesClass attributes in test files, helping maintain consistency in the test codebase by avoiding these coverage-related attributes.
The rule operates only on files ending with 'Test.php' and provides clear error messages with tips for resolving violations.

[PHPStan] Add rule to forbid test coverage attributes

---

.phpstan/ForbidEmptyRule.php
.phpstan/extension.neon
src/agent/src/MockAgent.php
src/agent/src/StructuredOutput/AgentProcessor.php
src/platform/src/Bridge/Anthropic/ModelClient.php

[PHPStan] Add rule to forbid empty() usage and replace all existing empty() calls

---

src/platform/src/Bridge/Anthropic/Claude.php
src/platform/tests/Bridge/Anthropic/ClaudeTest.php

| Issues        | Follows #667

[Platform][Anthropic] Modify Claude constructor `max_tokens` handling 

---

src/platform/src/Bridge/Ollama/Ollama.php
src/platform/tests/Bridge/Ollama/OllamaTest.php

| Docs?         | yes/no 
| Issues        |  - 
The current regex for QWEN models does not cover model size notation like `qwen3:32b` or `qwen3-coder:32b`.
I changed the regular expression to support notations with model sizes.

[Platform][Ollama] Better regex for qwen tool pattern

---

demo/README.md

[Demo] Extend demo readme for MCP example testing

---

examples/anthropic/stream.php
examples/bootstrap.php
examples/cerebras/stream.php
examples/gemini/stream.php
examples/mistral/stream.php
examples/ollama/stream.php
examples/openai/stream.php
examples/vertexai/stream.php

Extract repeated streaming pattern into reusable print_stream function in examples/bootstrap.php and update all streaming examples to use it.

 Refactor examples to use `print_stream` helper function

---

src/agent/composer.json
src/agent/src/InputProcessor/SystemPromptInputProcessor.php
src/agent/tests/InputProcessor/SystemPromptInputProcessorTest.php
src/ai-bundle/composer.json
src/ai-bundle/src/AiBundle.php
src/ai-bundle/tests/DependencyInjection/AiBundleTest.php

| New feature?  | yes/no
| Docs?         |  no 
This is a follow up of https://github.com/symfony/ai/pull/514 with a suggestion of using TranslatableMessage instance for prompts rather than the need in SystemPromptInputProcessor constructor of
- A boolean enableTranslation
- A domain
Since we're passing a TranslatableMessage this also allow to use translation parameters.
cc @OskarStark that was the suggestion in https://github.com/symfony/ai/pull/514#issuecomment-3299514958

[Agent] Allow translatable prompts in `SystemPromptInputProcessor`

---

src/agent/src/Toolbox/AgentProcessor.php
src/agent/tests/Toolbox/AgentProcessorTest.php

| Issues        | Fix https://github.com/symfony/ai/issues/678
This removes the exception that was thrown when models don't support tool calling capabilities, allowing AgentProcessor to work with any model regardless of their declared capabilities.

[Agent] Remove tool calling capability validation from `AgentProcessor`

---

examples/bedrock/chat-claude.php
examples/bedrock/image-claude-binary.php
examples/bedrock/toolcall-claude.php
src/platform/src/Bridge/Bedrock/Anthropic/Claude.php
src/platform/src/Bridge/Bedrock/Anthropic/ClaudeModelClient.php
src/platform/src/Bridge/Bedrock/Anthropic/ClaudeResultConverter.php
src/platform/tests/Bridge/Bedrock/Anthropic/ClaudeResultConverterTest.php
src/platform/tests/Bridge/Bedrock/Anthropic/ClaudeTest.php

We should not use classes from other platforms/stores, which will be standalone packages in the future.

[Platform][Bedrock] Use dedicated  model class

---

src/platform/src/Bridge/ElevenLabs/ElevenLabsClient.php
src/platform/tests/Bridge/ElevenLabs/ElevenLabsClientTest.php

[Platform][ElevenLabs] Fix option handling

---

examples/bootstrap.php
examples/runner

 Improve example output, mostly for errors

---

src/platform/src/Bridge/OpenAi/Gpt/ResultConverter.php
src/platform/src/Exception/BadRequestException.php
src/platform/tests/Bridge/OpenAi/Gpt/ResultConverterTest.php

| Issues        | Fix #528
I've noted an interesting initiative at https://github.com/symfony/ai/pull/574 to handle non-valid response codes in a more structured and scalable way. This approach makes sense to me, but it may require further reflection. With this PR, I aim to contribute a humble and specific use case for OpenAI, along with an Exception class that could be reused for the other bridges.

[Platform][OpenAI] Improve error reporting for Bad Request

---

.github/workflows/integration-tests.yaml
src/ai-bundle/config/services.php
src/ai-bundle/src/AiBundle.php
src/ai-bundle/tests/DependencyInjection/AiBundleTest.php
src/platform/src/Bridge/Cerebras/PlatformFactory.php
src/platform/src/Bridge/Voyage/PlatformFactory.php

| Issues        | Follows #640 

[AI Bundle] Fix service registration

---

.github/workflows/integration-tests.yaml
src/mcp-bundle/config/services.php

[MCP Bundle] Fix bundle config

---

src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php
src/platform/src/Bridge/OpenAi/Gpt/ResultConverter.php

Instead of always showing `Response does not contain any content.` or `Response does not contain choices.`, this MR exposes the original error message from Gemini/OpeNAI.
For example: `Error 400 - INVALID_ARGUMENT: A schema in GenerationConfig in the request exceeds the maximum allowed nesting depth.`.

[Platform][Gemini+OpenAI] Show error details to simplify localization of the cause

---

src/platform/tests/Bridge/Gemini/Gemini/ResultConverterTest.php
src/platform/tests/Bridge/OpenAi/Gpt/ResultConverterTest.php

| Issues        | Follows #608

[Platform] Add error handling tests

---

src/ai-bundle/config/options.php
src/ai-bundle/tests/DependencyInjection/AiBundleTest.php

| Issues        | - 
In #712, support for Ollama models with colon notation was added.
However, in the bundle configuration, `parse_url()` incorrectly treated the part before the colon as a URI scheme and discarded it.
As a result, model names were normalized to an empty or incomplete string, causing configuration errors.
```php
$parsed = parse_url('qwen3:0.6b'); // ['path' => '0.6b', 'scheme' => 'qwen' ]
$model = $parsed['path']; // "0.6b" ❌
```
This change ensures that model names written in colon notation are preserved correctly when parsing bundle configuration, allowing proper usage of Ollama models in Symfony projects.

[AI Bundle] Add parsing of model names with colon notation in config

---

src/ai-bundle/doc/index.rst

| Issues        | Follows #640 
Replace deprecated class and constant-based model configuration with plain string syntax across all examples in the AI Bundle documentation.

[AI Bundle] Update documentation to use plain string model syntax

---

demo/config/packages/ai.yaml
demo/prompts/stream-chat.txt
examples/misc/prompt-json-file.php
examples/misc/prompt-text-file.php
fixtures/prompts/code-reviewer.json
fixtures/prompts/helpful-assistant.txt
src/agent/src/InputProcessor/SystemPromptInputProcessor.php
src/agent/tests/InputProcessor/SystemPromptInputProcessorTest.php
src/ai-bundle/config/options.php
src/ai-bundle/doc/index.rst
src/ai-bundle/src/AiBundle.php
src/ai-bundle/tests/DependencyInjection/AiBundleTest.php

Support files like:
```json
{
"role": "You are an expert code reviewer with deep knowledge of software engineering best practices, design patterns, and code quality.",
"responsibilities": [
"Review code for bugs and potential issues",
"Suggest improvements for code quality and maintainability",
"Identify security vulnerabilities",
"Recommend better design patterns when appropriate",
"Ensure code follows language-specific best practices"
],
"tone": "constructive and educational",
"approach": "Provide thorough but concise feedback with specific suggestions and examples when helpful"
}
```
but also TXT or MD files are supported.
```yaml
ai: …
```

[AI Bundle][Agent] Add support for prompt as file

---

examples/vertexai/toolcall.php
src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php
src/platform/src/Bridge/VertexAi/Gemini/ResultConverter.php
src/platform/tests/Bridge/Gemini/Gemini/ResultConverterTest.php
src/platform/tests/Bridge/VertexAi/Gemini/ResultConverterTest.php

| Issues        |
The Gemini API may return multiple content parts even if a tool call is desired. For example, one content part can be an explanation why the tool was called. This PR adds support for this by first checking if any content part is a `functionCall`. If so, all other content parts are discarded and the function/tool call is processed.

[Platform][Gemini] Do tool call if any `contentPart` is a `functionCall`

---

examples/openai/agent-as-tool.php

[OpenAI] Add Agent-as-Tool example

---

src/store/src/Bridge/ClickHouse/Store.php
src/store/src/Bridge/Local/InMemoryStore.php
src/store/src/Bridge/SurrealDb/Store.php

| Issues        | Fix https://github.com/symfony/ai/pull/366#issuecomment-3364966018

[Store] Do not finalize the classes anymore

---

src/agent/doc/index.rst
src/agent/src/Toolbox/Event/ToolCallFailed.php
src/agent/src/Toolbox/Event/ToolCallSucceeded.php
src/agent/src/Toolbox/Toolbox.php
src/agent/tests/Toolbox/ToolboxEventDispatcherTest.php

| Issues        | Fix #680
This PR dispatches three new events around tool calling.

[Agent] Dispatch more tool call events

---

examples/compose.yaml
examples/rag/redis.php
src/ai-bundle/config/options.php
src/ai-bundle/src/AiBundle.php
src/ai-bundle/tests/DependencyInjection/AiBundleTest.php
src/store/CHANGELOG.md
src/store/composer.json
src/store/src/Bridge/Redis/Distance.php
src/store/src/Bridge/Redis/Store.php
src/store/tests/Bridge/Redis/StoreTest.php

| Issues        |
I continue to bench different stores, and the next one is Redis
```console
$ php rag/redis.php                                                                                                                   
Here are some movies that fit the theme of technology:                                                                                                                                      
1. **The Matrix**                                                                                                                                                                           
- **Description**: A hacker discovers the world he lives in is a …
```

[Store] Add Redis

---

src/ai-bundle/doc/index.rst

Added example loader class to indexer configuration because it's required and without it indexer could not be instantiated

[AI Bundle] Update documentation for indexer

---

examples/document/vectorizing-text-documents.php
src/store/src/Document/EmbeddableDocumentInterface.php
src/store/src/Document/Filter/TextContainsFilter.php
src/store/src/Document/FilterInterface.php
src/store/src/Document/Loader/InMemoryLoader.php
src/store/src/Document/LoaderInterface.php
src/store/src/Document/TextDocument.php
src/store/src/Document/Transformer/TextReplaceTransformer.php
src/store/src/Document/Transformer/TextSplitTransformer.php
src/store/src/Document/Transformer/TextTrimTransformer.php
src/store/src/Document/TransformerInterface.php
src/store/src/Document/Vectorizer.php
src/store/src/Document/VectorizerInterface.php
src/store/src/Indexer.php
src/store/tests/Document/Filter/TextContainsFilterTest.php
src/store/tests/Document/Loader/InMemoryLoaderTest.php
src/store/tests/Document/Loader/RssFeedLoaderTest.php
src/store/tests/Document/Loader/TextFileLoaderTest.php
src/store/tests/Document/TextDocumentTest.php
src/store/tests/Document/Transformer/ChainTransformerTest.php
src/store/tests/Document/Transformer/ChunkDelayTransformerTest.php
src/store/tests/Document/Transformer/TextReplaceTransformerTest.php
src/store/tests/Document/Transformer/TextSplitTransformerTest.php
src/store/tests/Document/Transformer/TextTrimTransformerTest.php
src/store/tests/Document/VectorizerTest.php
src/store/tests/IndexerTest.php

| Bug fix?      |no
| Issues        | Fix #18 
In an effort to support user land objects for the store, this PR introduces an `Embeddable` interface instead of relying on the `TextDocument` class. Please note this interface would require php ^8.4, as it uses interface properties. I chose this approach so as to introduce minimal change to the existing `TextDocument` class and usages. Instead of `content`, an `Embeddable` document has a `data` property. Any type embeddable document class can implement a hook for the `data` property if needed.
This PR also introduces union types for the document IDs so as to not make assumptions about the ID type.

[Store] Introduce `EmbeddableDocumentInterface`

---

src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php
src/platform/src/Bridge/VertexAi/Gemini/ResultConverter.php
src/platform/tests/Bridge/Gemini/Gemini/ResultConverterTest.php
src/platform/tests/Bridge/VertexAi/Gemini/ResultConverterTest.php

| Issues        | Fix #730
Fix handling of inlineData as Binary response in ResultConverter of Google Gemini.

[Platform][Gemini][VertexAI] Handle `inlineData`

---

examples/document/vectorizing-text-documents.php
src/store/src/Document/Vectorizer.php
src/store/src/Document/VectorizerInterface.php
src/store/src/Indexer.php
src/store/tests/Document/VectorizerTest.php

Replace separate vectorizeTextDocuments() and vectorize(string) methods with a single vectorize() method that handles:
- string -> Vector
- array<string> -> array<Vector>
- TextDocument -> VectorDocument
- array<TextDocument> -> array<VectorDocument>
Add PHPStan conditional return types for proper type inference. Add validation to ensure arrays contain only strings or TextDocuments. Update all usages across codebase including tests and examples.
cc @paulinevos

[Store] Unify `Vectorizer` methods into single `vectorize()` method

---

demo/src/Blog/Command/StreamCommand.php
demo/tests/Blog/Command/StreamCommandTest.php

Used this to test CLI profiler with streams, but might also be helpful for some and is a low effort thing to maintain going forward :)

[Demo] Add stream example command

---

src/platform/src/Bridge/DockerModelRunner/Completions/ResultConverter.php
src/platform/src/Bridge/Scaleway/Llm/ResultConverter.php

Remove try-catch blocks for JsonException that were only needed for Symfony 6.4 compatibility in stream processing methods.

[Platform] Remove Symfony 6.4 compatibility code

---

src/ai-bundle/doc/index.rst

[AI Bundle] Document all console commands

---

examples/.env
examples/deepseek/chat.php
examples/deepseek/reason.php
examples/deepseek/stream.php
examples/deepseek/structured-output-clock.php
examples/deepseek/token-metadata.php
examples/deepseek/toolcall-stream.php
examples/deepseek/toolcall.php
src/ai-bundle/config/services.php
src/ai-bundle/src/AiBundle.php
src/platform/src/Bridge/DeepSeek/DeepSeek.php
src/platform/src/Bridge/DeepSeek/ModelCatalog.php
src/platform/src/Bridge/DeepSeek/ModelClient.php
src/platform/src/Bridge/DeepSeek/PlatformFactory.php
src/platform/src/Bridge/DeepSeek/ResultConverter.php
src/platform/src/Bridge/DeepSeek/TokenOutputProcessor.php
src/platform/src/Exception/InvalidRequestException.php
src/platform/tests/Bridge/DeepSeek/DeepSeekTest.php
src/platform/tests/Bridge/DeepSeek/ModelCatalogTest.php
src/platform/tests/Bridge/DeepSeek/ModelClientTest.php
src/platform/tests/Bridge/DeepSeek/ResultConverterTest.php

| Docs?         | yes/no 
| Issues        | Fix #539 

[Platform] Add DeepSeek

---

src/ai-bundle/config/options.php
src/ai-bundle/src/AiBundle.php
src/ai-bundle/tests/DependencyInjection/AiBundleTest.php

Added dbal connection to ai-bundle postgres store configuration.
Now it can be configured either with DSN or Doctrine dbal connection service.

[AI Bundle][Postgres] Add `dbal_connection` configuration

---

docs/components/agent.rst
docs/components/platform/gemini-server-tools.rst
docs/components/platform/vertexai-server-tools.rst
docs/components/store.rst

 Fix documentation errors

---

docs/bundles/ai-bundle.rst
docs/components/agent.rst
docs/components/chat.rst
docs/components/platform.rst
docs/components/platform/gemini-server-tools.rst
docs/components/platform/vertexai-server-tools.rst
docs/components/platform/vertexai.rst
docs/components/store.rst

[Docs] Improve the overall documentation
