.github/workflows/code-quality.yaml, .github/workflows/unit-tests.yaml
Added Cache for Composer dependencies, either automatically with `ramsey/composer-install@v3` (for root dependencies), either manually with `actions/cache`, like we did on UX.
=> [CI] Cache Composer dependencies

src/platform/src/Bridge/Google/Contract/ToolNormalizer.php, src/platform/src/Bridge/Google/ModelHandler.php, src/platform/tests/Bridge/Google/Contract/ToolNormalizerTest.php
Cherry picking https://github.com/php-llm/llm-chain/pull/380
=> fix: Gemini multiple tools

src/store/doc/index.rst
| Bug fix?      | yes/no
| New feature?  | yes/no 
| Docs?         | yes/no 
=> add postgres in doc

examples/README.md
=> [Examples] add hint for using link tool with examples

src/platform/src/Bridge/Anthropic/Claude.php
=> [Platform] Add missing Anthropic models

src/ai-bundle/src/AIBundle.php
| Issues        | Fix #133
Make `security-core` optional + also register the attribute for autoconfiguration & throw to make sure no one tries to use the attribute without the listener (which would make one think that you have some access control when you don't).
=> [AIBundle] Remove security listener when missing dependencies

examples/anthropic/toolcall.php, examples/bedrock/toolcall-claude.php, examples/bedrock/toolcall-nova.php, examples/google/server-tools.php, examples/google/structured-output-clock.php, examples/google/toolcall.php, examples/mistral/toolcall-stream.php, examples/mistral/toolcall.php, examples/openai/structured-output-clock.php, examples/openai/toolcall-stream.php, examples/openai/toolcall.php, examples/store/mariadb-similarity-search-gemini.php, examples/store/mariadb-similarity-search.php, examples/store/meilisearch-similarity-search.php, examples/store/memory-similarity-search.php, examples/store/mongodb-similarity-search.php, examples/store/pinecone-similarity-search.php, examples/store/postgres-similarity-search.php, examples/store/qdrant-similarity-search.php, examples/toolbox/brave.php, examples/toolbox/serpapi.php, examples/toolbox/tavily.php, examples/toolbox/weather-event.php, src/agent/CHANGELOG.md, src/agent/src/Toolbox/Toolbox.php, src/agent/tests/Toolbox/ToolboxTest.php
This is just not useful other than in simplified examples - and not even there, see #160
=> [Agent][Examples] Remove Toolbox::create(...)

examples/mistral/chat-multiple.php
Forgot about that, but wanted at least to add one example.
Sometimes with a full stop, but always blue. :man_shrugging:
=> [Examples] Add example for choices

demo/tests/Blog/LoaderTest.php, demo/tests/Blog/PostTest.php, demo/tests/SmokeTest.php, src/ai-bundle/tests/Security/IsGrantedToolAttributeListenerTest.php
=> [Demo][Agent] Remove `declare(strict_types=1)`

examples/composer.json
Referring to https://github.com/CodeWithKyrian/transformers-php/issues/88
=> [Examples] Bump TransformersPHP lib to get rid off one setup error

src/store/tests/Bridge/Azure/SearchStoreTest.php, src/store/tests/Bridge/ChromaDB/StoreTest.php, src/store/tests/Bridge/MongoDB/StoreTest.php, src/store/tests/Bridge/Pinecone/StoreTest.php, src/store/tests/Bridge/Postgres/StoreTest.php
=> [Store] Add missing unit tests

src/store/src/InMemoryStore.php, src/store/tests/InMemoryStoreTest.php
| Issues        | Fix #187 ... 
This PR fixes #187, the issue where cosine similarity values were incorrectly treated as distances in the InMemoryStore::query() method, resulting in reversed result ordering. 
The fix converts cosine similarity to distance using `1-similarity`, which is the common conversion between similarity and distance.
Ensuring consistent sorting behavior across all strategies. Includes updated unit tests to validate.
=> [Store][InMemory] Fix cosine similarity sorting

src/agent/tests/ChatTest.php
=> [Agent] Add unit tests for `Chat`

.github/workflows/fabbot.yaml
=> [CI] Add Fabbot as a GitHub Actions

src/platform/src/Bridge/Mistral/Llm/ResultConverter.php, src/platform/src/Bridge/OpenAI/GPT/ResultConverter.php
| Issues        | N/A 
php-cs-fixer 3.85 has been released with a bunch of new rules, this fixes the 2 new violations
=> [Platform] Fix coding style

src/mcp-bundle/config/options.php, src/mcp-bundle/config/services.php, src/mcp-bundle/src/McpBundle.php, src/mcp-sdk/src/Capability/Tool/CollectionInterface.php, src/mcp-sdk/src/Capability/ToolChain.php, src/mcp-sdk/src/Server/RequestHandler/ToolListHandler.php
| Issues        | Fix #10  
The page size was hardcoded to 20 elements, now users can configure it in the mcp bundle. Passing null value will disable pagination and fetch all entries.
=> [MCP SDK][MCP Bundle] Add parameter for pagination and allow disabling pagination

src/ai-bundle/src/Profiler/DataCollector.php, src/ai-bundle/templates/data_collector.html.twig
=> [AI Bundle] Fix profiler template reference

examples/rag/neo4j.php
=> [Examples] Fix OpenAI and GPT namespaces in Neo4j RAG example

src/store/tests/Bridge/Postgres/StoreTest.php
| Issues        | Refs #235
This adds comprehensive test coverage for the new custom where expression feature merged in PR #235:
- Test custom where expression without maxScore
- Test custom where expression combined with maxScore
- Test custom where expression with custom parameters
cc @lyrixx
=> [Store][Postgres] Add tests for custom where expression

.php-cs-fixer.dist.php
| Issues        | Follows #245 
=> Include .phpstan/ folder in PHP-CS-Fixer configuration

examples/memory/mariadb.php, examples/rag/mariadb-gemini.php, examples/rag/mariadb-openai.php
=> [Examples] Fix MariaDB parallel execution

.phpstan/ForbidNativeExceptionRule.php
=> Fix CS on PHPStan rule

demo/.env, demo/README.md, demo/compose.yaml, demo/composer.json, demo/config/packages/chromadb.yaml
| Docs?         | changed
The docker setup is a bit annoying when it comes to working with `link` tool and local library versions - Symfony CLI makes it easier.
=> [Demo] Switch to Symfony CLI for demo

src/agent/tests/InputProcessor/ModelOverrideInputProcessorTest.php, src/agent/tests/StructuredOutput/AgentProcessorTest.php, src/agent/tests/Toolbox/AgentProcessorTest.php, src/agent/tests/Toolbox/MetadataFactory/ChainFactoryTest.php, src/agent/tests/Toolbox/MetadataFactory/MemoryFactoryTest.php, src/agent/tests/Toolbox/MetadataFactory/ReflectionFactoryTest.php, src/agent/tests/Toolbox/ToolboxTest.php, src/ai-bundle/tests/Security/IsGrantedToolAttributeListenerTest.php, src/platform/tests/Bridge/OpenAi/DallE/Base64ImageTest.php, src/platform/tests/Bridge/OpenAi/DallE/UrlImageTest.php, src/platform/tests/Bridge/OpenAi/Gpt/ResultConverterTest.php, src/platform/tests/Contract/JsonSchema/Attribute/ToolParameterTest.php, src/platform/tests/Message/Content/AudioTest.php, src/platform/tests/Message/Content/BinaryTest.php, src/platform/tests/Message/Content/ImageTest.php, src/platform/tests/Result/BaseResultTest.php, src/platform/tests/Result/ChoiceResultTest.php, src/platform/tests/Result/RawResultAwareTraitTest.php, src/platform/tests/Result/TollCallResultTest.php, src/platform/tests/Vector/NullVectorTest.php, src/store/tests/Bridge/Meilisearch/StoreTest.php, src/store/tests/Bridge/Neo4j/StoreTest.php, src/store/tests/Bridge/Qdrant/StoreTest.php, src/store/tests/Bridge/SurrealDb/StoreTest.php, src/store/tests/Document/Loader/TextFileLoaderTest.php, src/store/tests/Document/Transformer/TextSplitTransformerTest.php
=> Use `$this` over `self::` in tests

src/store/doc/index.rst
=> [Store] Sort stores in doc

src/store/CHANGELOG.md
=> Store] Sort stores in CHANGELOG

src/platform/src/Bridge/Ollama/OllamaClient.php
=> [Platform] Throw exception when ollama model information cannot be retrieved

examples/.env, examples/cerebras/chat.php, examples/cerebras/stream.php, src/ai-bundle/src/AiBundle.php, src/platform/CHANGELOG.md, src/platform/doc/index.rst, src/platform/src/Bridge/Cerebras/Model.php, src/platform/src/Bridge/Cerebras/ModelClient.php, src/platform/src/Bridge/Cerebras/PlatformFactory.php, src/platform/src/Bridge/Cerebras/ResultConverter.php, src/platform/tests/Bridge/Cerebras/ModelClientTest.php, src/platform/tests/Bridge/Cerebras/ResultConverterTest.php
| Issues        | #16 
This PR adds support for the [Cerebras](https://inference-docs.cerebras.ai/) platform
=> [Platform] Add Cerebras

src/agent/src/Toolbox/Tool/Firecrawl.php
| Issues        | #270 
Hi 👋🏻 
As discussed in #270, the crawling part wasn't authenticated during the "status request" phase, this PR define a closure to check the status with the API Key.
=> [Agent] Firecrawl crawling fix

src/ai-bundle/templates/data_collector.html.twig
=> [AiBundle] Fix profiler with array arguments

src/platform/src/Bridge/OpenAi/Gpt.php
=> [Platform] Remove GPT-5 Chat model tool call capabilities

examples/runner
=> [Examples] Filter out bootstrap files in examples runner

src/store/tests/Bridge/ChromaDb/StoreTest.php
| Issues        | Follows #340 
fyi @valx76
=> [Store][ChromaDB] Add tests for query filtering

src/ai-bundle/config/options.php
=> [AI Bundle] Fix indentation

src/ai-bundle/src/AiBundle.php, src/ai-bundle/tests/DependencyInjection/AiBundleTest.php
| Issues        | Fix #355 
Small fix related to agent injection.
=> [AIBundle] Fix single agent alias

examples/compose.yaml
=> [Examples] Fix environment variables

examples/rag/milvus.php
=> [Examples][Milvus] Fix RAG example

examples/compose.yaml
=> [Examples] Use `getmeili/meilisearch:v1.19`

examples/compose.yaml
=> [Examples] Add `MongoDB` to `compose.yaml`

examples/.env, examples/compose.yaml, examples/composer.json
Hi 👋🏻 
As discussed in #335, here's the update for `MongoDB` in example (both `.env` and package).
=> [Examples] Improve mongodb

src/platform/CHANGELOG.md
=> [Platform] Remove blank lines in CHANGELOG

src/agent/src/Attribute/AsInputProcessor.php, src/agent/src/Attribute/AsOutputProcessor.php, src/ai-bundle/config/services.php, src/ai-bundle/doc/index.rst, src/ai-bundle/src/AiBundle.php, src/ai-bundle/src/DependencyInjection/ProcessorCompilerPass.php, src/ai-bundle/tests/DependencyInjection/ProcessorCompilerPassTest.php
| Docs?         | TODO
Reference https://github.com/symfony/ai/issues/346#issuecomment-3218405736
cc @chr-hertel (@OskarStark) I'd like your opinion on this
- I added a priority param, I feel like it could be useful to handle the order of the processor
- I'd like your opinion about what should be the default priority of the existing processor (agent_processor, structured_output_processor, system_prompt)
=> [AI Bundle][Agent] Add `#[AsInputProcessor]` and `#[AsOutputProcessor]`

examples/azure/embeddings.php, examples/bootstrap.php, examples/gemini/embeddings.php, examples/huggingface/feature-extraction.php, examples/misc/parallel-embeddings.php, examples/mistral/embeddings.php, examples/openai/embeddings.php, examples/vertexai/embeddings.php, examples/voyage/embeddings.php
=> [Examples] Add and use `print_vectors()` function

src/store/composer.json
=> [Store] Add missing store keywords to `composer.json`

src/store/tests/Document/Transformer/ChunkDelayTransformerTest.php
=> [Store] Add comprehensive unit tests for `ChunkDelayTransformer`

src/store/src/Bridge/Weaviate/Store.php
| Issues        | Related to #335 
Small fix regarding the handling of `drop` (empty content).
=> [Store] Fix Weaviate handling during drop

src/agent/.gitattributes, src/ai-bundle/.gitattributes, src/mcp-bundle/.gitattributes, src/platform/.gitattributes, src/store/.gitattributes
=> Ignore `CLAUDE.md` to `.gitattributes` files

src/platform/tests/Bridge/Replicate/ClientTest.php, src/platform/tests/Bridge/Replicate/Contract/LlamaMessageBagNormalizerTest.php, src/platform/tests/Bridge/Replicate/LlamaModelClientTest.php, src/platform/tests/Bridge/Replicate/LlamaResultConverterTest.php
=> [Platform][Replicate] Add tests

examples/composer.json, src/platform/composer.json
=> [Platform] Update codewithkyrian/transformers requirement to ^0.6.2

src/ai-bundle/doc/index.rst
=> [AI Bundle] Update documentation for translatable system prompts

demo/config/packages/ai.yaml
=> [Demo] Remove commented Anthropic platform configuration from config

.github/workflows/integration-tests.yaml
=> [Demo] Fix workflow working dirs

demo/src/Blog/FeedLoader.php
=> [Demo] Fix CS

.github/workflows/integration-tests.yaml
=> [CI] Fix demo

src/agent/phpunit.xml.dist, src/ai-bundle/phpunit.xml.dist, src/mcp-bundle/phpunit.xml.dist, src/mcp-sdk/phpunit.xml.dist, src/platform/phpunit.xml.dist, src/store/phpunit.xml.dist
=>  Update PHPUnit testsuite names to use package names

src/ai-bundle/src/AiBundle.php
=> [AI Bundle] Remove PHPStan ignore in AiBundle

src/platform/src/Bridge/Anthropic/Claude.php
=> [Platform] Revert change in Anthropic breaking easy model usage

src/mcp-bundle/src/Command/McpCommand.php
=> [MCP Bundle] Fix STDIO command to listen

src/platform/src/Bridge/Azure/Meta/PlatformFactory.php, src/platform/src/Bridge/Mistral/PlatformFactory.php
=> [Platform] ``#[\SensitiveParameter]` attribute on one line with parameter

src/ai-bundle/src/AiBundle.php
=> [AI Bundle] Fix service id

examples/openai/chat-with-string-options.php, src/platform/src/ModelCatalog/AbstractModelCatalog.php, src/platform/tests/DynamicModelCatalogTest.php, src/platform/tests/ModelCatalog/AbstractModelCatalogTest.php
=> [Platform] Fix integer options

src/agent/tests/InputTest.php, src/agent/tests/OutputTest.php, src/chat/tests/Bridge/HttpFoundation/SessionStoreTest.php, src/chat/tests/Bridge/Local/CacheStoreTest.php, src/chat/tests/Bridge/Local/InMemoryStoreTest.php
=> [Agent][Chat] Add more unit tests
